## Append samples you want in your CSV to this file as resources ##
resources:
- databaser_v1alpha1_databaseinstance.yaml
- databaser_v1alpha1_database.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
